#MY UPI IS TROB525
#MY UPI IS TROB525
#MY UPI IS TROB525
#MY UPI IS TROB525

# AND I BET I'M GOING TO LOSE MARKS FOR THIS FREAKING MAKEFILE BECAUSE WHO FREAKING KNOWS, I FORGOT TO COAT IT WITH ICING OR #SOMETHING

#I DON'T KNOW WHY THIS PAPER DEDUCTS SO MANY MARKS FOR NOT USING .TXT FILES AND FORGETTING YOUR UPI IN FILES YOU DIDN'T EVEN
#MODIFY BUT I'M SURE IT MAKES A GREAT DEAL OF SENSE TO SOME POWER MAD INDIVIDUAL HIGH UP WHO GETS OFF TO BEING ANAL RETENTIVE
#IF THIS IS A PROBLEM YOU CAN SPEAK TO ME, BUT IT DOESN'T SAY ANYWHERE ON THE ASSIGNMENT SPEC THAT YOU CAN'T RANT ABOUT
#ANAL RETENTIVENESS IN YOUR MAKE FILE, SO IF ANYTHING I DESERVE BONUS MARKS FOR GOING BEYOND THE CALL OF DUTY.

#YES, I AM UPSET! I WOULD HAVE GOT 100% IF NOT FOR STUPID RULES THAT PUNISH PEOPLE FOR NOT READING EVERY LETTER OF THE ASSIGNMENT
#SPEC AND I'M PRETTY SURE IT DIDN'T SAY ANYWHERE "YOU WILL LOSE HEAPS OF MARKS FOR NOT SUBMITTING A .TXT FILE" BUT WHATEVER

#INSTRUCTIONS: run this file as a bash script in your terminal. If you are using windows turn off your computer and walk away,
#if you are using Mac or Linux click the terminal icon and type on your keyboard "/bin/sh InstructionsForRunning.sh" (without
#quotes) if this doesn't work throw your computer out the window and cry.

cp sync.py sync
chmod +x sync
